project:
  type: website

website:
  title: "CIS375 Advanced Web Development"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - assignments.md
      - policies.md
      - resources.md
      - tips.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true



