---
title: Course Schedule 
toc: false
---

Date|Topics & Activites|Assignments
--|---|---|---
14 & 16 Jan.|Course Description & CIS 275 Project Review
21 & 23 Jan.|HTML & CSS Review
28 & 30 Jan.|Layout Techniques & Responsive Web Design
4 & 6 Feb.|Responsive Design & Development
11 & 13 Feb.|Content Management Systems|**RWD Project Due 13 Feb.**
18 & 20 Feb.|Wordpress & Server Setup
25 & 27 Feb.|Lab: CMS Project
4 & 6 Mar.|Lab:CMS Project
11 & 13 Mar.|SPRING BREAK
18 & 20 Mar.|Lab:CMS Project|**CMS Project Due 20 Mar.**
25 & 27 Mar.|Web App Research & Development
1 & 3 Apr.|Lab: Web App
8 & 10 Apr.|Framework Troubleshooting
15 & 17 Apr.|Lab: Web App
22 & 24 Apr.|Lab: Web App
3 May 5pm|NO FINAL EXAM|**Web App Due 3 May at 5pm**

: {.striped .hover}

### Note on the schedule

*Keep in mind that some of this schedule could change throughout the semester. However, if anything changes I'll update this page, and I'll be sure to give you plenty of advance notice.*

## Course Materials

There are no required texts for this course. Numerous Internet resources will be provided as readings throughout the term. However, there are several texts that you will find immeasurably valuable if you actually want to effectively learn about this content. Please ask me if you would like more reading material during the term.

Instead of purchasing books, you will need to appropriate a web hosting package and a USB flash drive. I will provide you with full details regarding this process at the appropriate time.
